COCO_CLASSES = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

COCO_SUPERCLASSES = (
    "person",
    "vehicle",
    "vehicle",
    "vehicle",
    "vehicle",
    "vehicle",
    "vehicle",
    "vehicle",
    "vehicle",
    "outdoor",
    "outdoor",
    "outdoor",
    "outdoor",
    "outdoor",
    "animal",
    "animal",
    "animal",
    "animal",
    "animal",
    "animal",
    "animal",
    "animal",
    "animal",
    "animal",
    "accessory",
    "accessory",
    "accessory",
    "accessory",
    "accessory",
    "sports",
    "sports",
    "sports",
    "sports",
    "sports",
    "sports",
    "sports",
    "sports",
    "sports",
    "sports",
    "kitchen",
    "kitchen",
    "kitchen",
    "kitchen",
    "kitchen",
    "kitchen",
    "kitchen",
    "food",
    "food",
    "food",
    "food",
    "food",
    "food",
    "food",
    "food",
    "food",
    "food",
    "furniture",
    "furniture",
    "furniture",
    "furniture",
    "furniture",
    "furniture",
    "electronic",
    "electronic",
    "electronic",
    "electronic",
    "electronic",
    "electronic",
    "appliance",
    "appliance",
    "appliance",
    "appliance",
    "appliance",
    "indoor",
    "indoor",
    "indoor",
    "indoor",
    "indoor",
    "indoor",
    "indoor",
)